config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  root 'proposals#index'
  resources :proposals
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/proposal.rb
class Proposal < ApplicationRecord
    has_one :place
    accepts_nested_attributes_for :place, allow_destroy: true
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_proposal, only: [:show, :edit, :update, :destroy]
  before_action :set_env, only: [:new, :create, :index, :show, :edit, :update]

  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.where(end_time:Time.zone.now..(Date.today+1).end_of_day)

    # binding.pry
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
  end

  # GET /proposals/new
  # TODO varidate date
  def new
    # gon.maps_api = ENV['MAPS_KEY']
    @proposal = Proposal.new
    @place = Place.new
  end

  # GET /proposals/1/edit
  def edit
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @place = Place.create(place_params)
    @proposal = Proposal.new(proposal_params)
    # binding.pry

    respond_to do |format|
      if @proposal.save && @place.update(proposal_id: @proposal.id)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render :show, status: :created, location: @proposal }
      else
        format.html { render :new }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proposals/1
  # PATCH/PUT /proposals/1.json
  def update
    respond_to do |format|
      if @proposal.update(proposal_params)
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { render :show, status: :ok, location: @proposal }
      else
        format.html { render :edit }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal.destroy
    respond_to do |format|
      format.html { redirect_to proposals_url, notice: 'Proposal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proposal
      @proposal = Proposal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proposal_params
      params.require(:proposal).permit(:detail, :end_time);
    end

    def place_params
      # binding.pry
      params.require(:place).permit(:name, :place_url, :point, :image_url);
    end

    def set_env
      gon.maps_api = ENV['MAPS_KEY']
      headers['Access-Control-Allow-Origin'] = 'https://maps.googleapis.com/*'
    end
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.haml
= javascript_include_tag 'search.js'

#store_search
  %label お店を検索する
  %input(type="text" placeholder="お店の名前" id="store_search__input")/
  #map
#store_list.flex

= form_with(model: @proposal, local: true, class: "form_wrapper") do |form|
  - if @proposal.errors.any?
    #error_explanation
      %h2
        = pluralize(@proposal.errors.count, "error")
        prohibited this proposal from being saved:
      %ul
        - @proposal.errors.full_messages.each do |message|
          %li= message
  = form.label :end_time, "何時まで滞在するか："
  = form.datetime_select :end_time, min: DateTime.now.strftime("%y-%m-%dT%H:%M:%S.000") ,minute_step: 15
  %br
  = form.label :detail, "詳細："
  %br
  = form.text_area :detail, rows: "6"

  = fields_for :place, (@place) do |place_form|
    = place_form.text_field :place_url, class: :hidden, id: :place_url
    = place_form.text_field :name, class: :hidden, id: :place_name
    = place_form.text_field :point, class: :hidden, id: :place_position
    = place_form.text_field :image_url, class: :hidden, id: :place_img

  .actions
    = form.submit

app/views/proposals/edit.html.haml
%h1 Editing Proposal
= render 'form', proposal: @proposal
= link_to 'Show', @proposal
|
= link_to 'Back', proposals_path

app/views/proposals/index.html.haml
%p#notice= notice
%h1 Proposals
%table
  %thead
    %tr
      %th{:colspan => "3"}
  #proposal_list.flex
    - @proposals.each do |proposal|
      %div{id: "proposal#{proposal.id}"}
        = image_tag proposal.place.image_url, alt: proposal.place.name
        %h4 #{proposal.place.name}
        %p #{proposal.end_time.strftime("%H:%M")} まで滞在予定
%br/
.new_btn
  = link_to '席をシェアする', new_proposal_path

app/views/proposals/new.html.haml
%h1 相席を提案する
= render 'form', proposal: @proposal
= link_to 'Back', proposals_path

app/views/proposals/show.html.haml
%p#notice= notice
= link_to 'Edit', edit_proposal_path(@proposal)
|
= link_to 'Back', proposals_path